### PR TITLE
Use report-uri.com to collect csp reports and add Feature-Policy

### PR DESCRIPTION
**Pull request by zero-24**
Use report-uri.com to collect csp reports and add Feature-Policy

### CODE REVIEW

**Comment by mbabker** [comment]
How exactly was this feature policy decided upon?  None of the chosen features to disable are actually used on this website in the first place.

**Comment by zero-24** [comment]
> How exactly was this feature policy decided upon? None of the chosen features to disable are actually used on this website in the first place.

That is the plan ;) When not needed it can be disabled so an XSS script can not use the features too.

**Comment by mbabker** [comment]
Maybe I'm missing something about this header's purpose, but it doesn't seem like it has any practical use when you already have a CSP in place as short of some form of response hijacking there isn't a practical XSS vector this would prevent.  And if I'm being realistic here, looking at the list of features on MDN and what this pull request provides, I'd say a feature like `sync-xhr` is in more need of a defined policy than `accelerometer` as I can think of at least three subdomains that make absolutely zero use of AJAX based functionality and as a result should not be able to create a XHR request.  So at face value, not really understanding the methodology here, this just looks like adding more security configurations that cover hypothetical concerns more than practical concerns.

**Comment by mbabker** [comment]
(Basically I'm just trying to make sure I'm clear on the actual changes this is bringing along and not just blindly merging something because a pull request was proposed, not trying to say that the change itself is bad or pointless).

**Comment by zero-24** [comment]
I get your point. I have now removed the feature policy from this PR and just update it to the new endpoint will to so for the other PRs too, will take some more time do a site by site consideration for that header and send a new PR on that.

**Comment by zero-24** [comment]
Thanks @mbabker 👍

**Pull request merged**
