### PR TITLE
Add default http security header using .htaccess

### PR DESCRIPTION
**Pull request by zero-24**
#### Summary of Changes

With this PR we set the basic http security headers

#### Open points / questions

- [ ] CSP rules (needs to wait until we have a csp-reporter place)

### CODE REVIEW

**Comment by zero-24** [comment]
hmm does this domain sit also on the server with the broken mod_header module?
https://securityheaders.io/?q=api.joomla.org&hide=on&followRedirects=on

**Comment by mbabker** [comment]
No I just haven't gotten to pushing a deploy button yet.

**Comment by zero-24** [comment]
Sorry I just want to be sure.

**Comment by mbabker** [comment]
Not to mention, now that I look at that job's configuration, `.htaccess` isn't part of the deployed assets anyway.  So, it'll get there at some point.

**Comment by mbabker** [comment]
Made the `.htaccess` change now on the server.

**Comment by zero-24** [comment]
Thanks that worked.

**Pull request merged**
